### ISSUE TITLE
How to write the post request by using this template

### ISSUE THREAD

**Issue by badkk** [openfaas-incubator/node8-express-template#3]
I'm writing the post function, I just use the 
```javascript
    app.post('/upload', function (req, res) {});
```
but it did not work.
Anybody knows the right way to write post code?

**Comment by alexellis** [comment]
Hi @LucasDvp you should post the body, or upload the binary artifact to Minio or S3, then only send the URL to the function. Assume your function is read-only and stateless.

What data were you trying to post?

Alex

**Comment by badkk** [comment]
Sorry about the delay, this issue has been resolved.
And the problem is like @alexellis said, it's the way I bad requested from *Postman*.

**Comment by alexellis** [comment]
No probs!
